# Generated by Django 4.1.2 on 2022-12-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.CharField(max_length=10)),
                ('transmicion', models.CharField(max_length=30)),
                ('kilometraje', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=11)),
                ('horario', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('calidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motores', models.CharField(max_length=50)),
                ('neumaticos', models.CharField(max_length=50)),
                ('llantas', models.CharField(max_length=50)),
                ('aceites', models.CharField(max_length=50)),
                ('baterias', models.CharField(max_length=50)),
                ('suspensiones', models.CharField(max_length=50)),
                ('autos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest.autos')),
                ('tiendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest.tienda')),
            ],
        ),
    ]
